countries = {
    "united-states": "États-Unis",
    "france": "France",
    "united-kingdom": "Royaume-Uni",
    "germany": "Allemagne",
    "switzerland": "Suisse",
    "spain": "Espagne",
    "canada": "Canada",
    "belgium": "Belgique",
    "australia": "Australie",
    "portugal": "Portugal",
    "russia": "Russie",
    "italy": "Italie",
    "reunion": "Réunion",
    "austria": "Autriche",
    "guadeloupe": "Guadeloupe",
    "netherlands": "Pays-Bas",
    "ireland": "Irlande",
    "martinique": "Martinique",
    "luxembourg": "Luxembourg",
    "french-guiana": "Guyane française",
    "new-caledonia": "Nouvelle Calédonie",
    "czech-republic": "République Tchèque",
    "french-polynesia": "Polynésie française",
    "morocco": "Maroc",
    "taiwan": "Taiwan",
    "tunisia": "Tunisie",
    "denmark": "Danemark",
    "saint-pierre-and-miquelon": "Saint-Pierre-et-Miquelon",
    "algeria": "Algérie",
    "senegal": "Sénégal",
    "hong-kong": "Hong Kong",
    "china": "Chine",
    "romania": "Roumanie",
    "mexico": "Méxique",
    "hungary": "Hongrie",
    "poland": "Pologne",
    "united-arab-emirates": "Émirats Arabes Unis",
    "saudi-arabia": "Arabie Saoudite",
    "lebanon": "Liban",
    "brazil": "Brézil",
    "greece": "Grèce",
    "turkey": "Turquie",
    "cote-d-ivoire": "Côte d'Ivoire",
    "singapore": "Singapour",
    "sweden": "Suède",
    "india": "Inde",
    "japan": "Japon",
    "slovenia": "Slovénie",
    "thailand": "Thailand",
    "quebec": "Canada",
    "bulgaria": "Bulgarie",
    "aruba": "Aruba",
    "costa-rica": "Costa-Rica",
    "monaco": "Monaco",
    "kuwait": "Koweit",
    "mayotte": "Mayotte",
    "south-korea": "Korée du Sud",
    "mauritius": "île Maurice",
    "السعودية": "Arabie Saoudite",
    "pakistan": "Pakistan",
    "dominican-republic": "République Dominicaine",
    "scotland": "Ecosse",
    "togo": "Togo",
    "cuba": "Cuba",
    "iraq": "Irak",
    "deutschland": "Allemagne",
    "chile": "Chili",
    "finland": "Finland",
    "peru": "Péru",
    "philippines": "Philippines",
    "norway": "Norvège",
    "trinidad-and-tobago": "Trinité-et-Tobago",
    "panama": "Panama",
    "israel": "Israël",
    "colombia": "Colombie",
    "gabon": "Gabon",
    "south-africa": "Afrique du Sud",
    "soviet-union": "Russie",
    "indonesia": "Indonésie",
    "ukraine": "Ukraine",
    "egypt": "Egypte",
    "qatar": "Qatar",
    "haiti": "Haïti",
    "allemagne": "Allemagne",
    "turkiye": "Turquie",
    "cameroon": "Cameroun",
    "bahrain": "Bahreïn",
    "cambodia": "Cambodge",
    "croatia": "Croatie",
    "serbia": "Serbie",
    "andorra": "Andorre",
    "el-salvador": "El-Salvador",
    "guinea": "Guinée",
    "world": "Tous",
    "jordan": "Jordanie",
    "nigeria": "Nigéria",
    "belgique": "Belgique",
    "mali": "Mali",
    "franciaorszag": "France",
    "magyarorszag": "Hongrie",
    "nagy-britannia": "Royaume-Uni",
    "portugalia": "Portugal",
    "spanyolorszag": "Espagne",
    "nemetorszag": "Allemagne",
    "frankreich": "France",
    "kazakhstan": "Kazakhstan",
    "republic-of-the-congo": "République du Congo",
    "svajc": "Suisse",
    "malaysia": "Malaisie",
    "belgien": "Belgique",
    "bourgogne-aube-nogent-sur-seine": "France",
    "wallis-and-futuna": "Wallis et Futuna",
    "belgie": "Belgique",
    "malawi": "Malawi",
    "vanuatu": "Vanuatu",
    "espagne": "Espagne",
    "royaume-uni": "Royaume-Uni",
    "aix-en-provence": "France",
    "bouches-du-rhone": "France",
    "spanien": "Espagne",
    "frankrijk": "France",
    "lithuania": "Lituanie",
    "armenia": "Arménie",
    "new-zealand": "Nouvelle-Zélande",
    "ecuador": "Équateur",
    "香港": "Hong Kong",
    "argentina": "Argentine",
    "burundi": "Burundi",
    "puerto-rico": "Porto Rico",
    "honduras": "Honduras",
    "cyprus": "Chypre",
    "venezuela": "Venezuela",
    "czech": "République Tchèque",
    "guyana": "Guyana",
    "etats-unis": "États-Unis",
    "australie": "Australie",
    "moldova": "Moldavie",
    "pays-bas": "Pays-Bas",
    "nederland": "Pays-Bas",
    "barbados": "Barbade",
    "oman": "Oman",
    "niederlande": "Pays-Bas",
    "united-states-of-america": "États-Unis",
    "malta": "Malte",
    "suriname": "Suriname",
    "virgin-islands-of-the-united-states": "Îles Vierges des États-Unis",
    "slovakia": "Slovaquie",
    "iceland": "Islande",
    "weltweit": "Tous",
    "worldwide": "Tous",
    "angleterre": "Angleterre",
    "global-market": "Tous",
    "الإمارات-العربية-المتحدة": "Émirats Arabes Unis",
    "all-over-the-world": "Tous",
    "island": "Islande",
}
